const products=[
 {id:'box-tasting',name:'The Tasting Box',desc:'Six pantry essentials for a first Italian evening.',price:89000,badge:'Best seller',image:'https://images.unsplash.com/photo-1556761223-4c4282c73f77?auto=format&fit=crop&w=900&q=80'},
 {id:'box-host',name:'The Host Box',desc:'A generous aperitivo edit for four to share.',price:129000,badge:'For gathering',image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'},
 {id:'box-gift',name:'The Little Gift',desc:'A considered trio, wrapped and ready to give.',price:59000,badge:'Under ₩60k',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80'},
 {id:'pasta',name:'Bronze-cut tagliatelle',desc:'Slow-dried in Gragnano, with a beautifully porous bite.',price:12000,image:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80'},
 {id:'oil',name:'Sicilian olive oil',desc:'Peppery extra virgin oil from a family grove.',price:28000,image:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80'},
 {id:'truffle',name:'White truffle salt',desc:'A tiny finishing touch with a remarkable aroma.',price:22000,image:'https://images.unsplash.com/photo-1515443961218-a51367888e4b?auto=format&fit=crop&w=900&q=80'},
 {id:'tomato',name:'Sun-ripened passata',desc:'Sweet, silky tomatoes from Campania.',price:15000,image:'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&q=80'},
 {id:'balsamic',name:'Modena balsamic',desc:'Aged and glossy, for cheese, fruit or a salad.',price:24000,image:'https://images.unsplash.com/photo-1472476442910-7aefb0d6e5c1?auto=format&fit=crop&w=900&q=80'},
 {id:'almonds',name:'Piedmont hazelnuts',desc:'Roasted IGP hazelnuts with a deep, clean crunch.',price:18000,image:'https://images.unsplash.com/photo-1599599810694-57a33b7f7b56?auto=format&fit=crop&w=900&q=80'}
];
const translations={ko:{announcement:'₩70,000 이상 주문 시 서울 무료 배송',navBoxes:'기프트 박스',navPantry:'팬트리',navStory:'브랜드 이야기',cart:'장바구니',heroEyebrow:'이탈리아의 의식 · 서울의 저녁',heroTitle:'당신의 식탁에<br>열리는 이탈리아.',heroText:'여섯 가지 특별한 식재료. 잊지 못할 저녁 한 번. 한국을 위해 이탈리아의 작은 생산자들을 큐레이션했습니다.',heroCta:'박스 둘러보기',heroNote:'서울 첫 드롭 · 150박스 한정',introEyebrow:'또 하나의 식료품점이 아닙니다',introTitle:'정성스럽게 편집한<br>완벽한 이탈리아의 저녁.',introText:'오래 보관할 수 있는 스페셜티 식재료에 간단한 의식, 서빙 노트와 아름다운 포장을 더했습니다.',boxesEyebrow:'박스 컬렉션',boxesTitle:'당신의 저녁을 고르세요',boxesText:'모든 박스에는 영문·한글 테이스팅 카드와 쉬운 서빙 가이드가 들어 있습니다.',pantryEyebrow:'나만의 테이블 만들기',pantryTitle:'여섯 가지 팬트리',pantryText:'하나의 스페셜티로 시작하거나 나만의 이탈리아의 밤을 구성하세요.',add:'담기',yourBag:'장바구니',items:'개',subtotal:'소계',checkout:'데모 주문하기',demoNote:'프로토타입 — 결제가 진행되지 않습니다.',shipping:'₩70,000 이상 무료 배송',join:'리스트 가입',joined:'테이스팅 리스트에 등록되었습니다.',footer:'한국을 위해 큐레이션한 이탈리아 미식의 의식.'}};
let lang='en',cart=JSON.parse(localStorage.getItem('vero-cart')||'{}');
const money=n=>`₩${n.toLocaleString('ko-KR')}`; const t=k=>(lang==='ko'&&translations.ko[k])||({add:'Add to bag',shipping:'Complimentary Seoul delivery over ₩70,000',joined:'You are on the tasting list.'}[k]||k);
function card(p){return `<article class="product-card">${p.badge?`<span class="badge">${p.badge}</span>`:''}<img src="${p.image}" alt="${p.name}" loading="lazy"><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" data-id="${p.id}">${t('add')}</button></div></div></article>`}
function render(){boxGrid.innerHTML=products.slice(0,3).map(card).join('');productGrid.innerHTML=products.slice(3).map(card).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(b.dataset.id));updateCart();document.querySelectorAll('[data-i18n]').forEach(e=>{const v=t(e.dataset.i18n);if(v!==e.dataset.i18n)e.innerHTML=v});}
function add(id){cart[id]=(cart[id]||0)+1;localStorage.setItem('vero-cart',JSON.stringify(cart));updateCart();toast(lang==='ko'?'장바구니에 담았습니다.':'Added to your bag.');}
function updateCart(){let count=0,total=0;cartItems.innerHTML='';Object.entries(cart).forEach(([id,qty])=>{const p=products.find(x=>x.id===id);if(!p)return;count+=qty;total+=p.price*qty;cartItems.innerHTML+=`<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="qty"><button data-q="-1" data-id="${id}">−</button>${qty}<button data-q="1" data-id="${id}">+</button></div></div></div>`});document.querySelectorAll('.qty button').forEach(b=>b.onclick=()=>{cart[b.dataset.id]=(cart[b.dataset.id]||0)+Number(b.dataset.q);if(cart[b.dataset.id]<=0)delete cart[b.dataset.id];localStorage.setItem('vero-cart',JSON.stringify(cart));updateCart()});cartCount.textContent=count;drawerCount.textContent=count;subtotal.textContent=money(total);shippingNote.textContent=total? (total>=70000?t('shipping'):lang==='ko'?`₩${(70000-total).toLocaleString()} 더 주문하면 무료 배송`:`${money(70000-total)} away from free Seoul delivery`):'';checkoutBtn.disabled=!count}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2500)}
const boxGrid=document.getElementById('boxGrid'),productGrid=document.getElementById('productGrid'),cartItems=document.getElementById('cartItems'),cartCount=document.getElementById('cartCount'),drawerCount=document.getElementById('drawerCount'),subtotal=document.getElementById('subtotal'),shippingNote=document.getElementById('shippingNote'),checkoutBtn=document.getElementById('checkoutBtn'),toastEl=document.getElementById('toast');
cartBtn.onclick=()=>{cartDrawer.classList.add('open');overlay.hidden=false};closeCart.onclick=()=>{cartDrawer.classList.remove('open');overlay.hidden=true};overlay.onclick=()=>closeCart.onclick();
checkoutBtn.onclick=()=>checkoutDialog.showModal();closeCheckout.onclick=()=>checkoutDialog.close();continueBtn.onclick=()=>checkoutDialog.close();checkoutForm.onsubmit=e=>{e.preventDefault();checkoutFormWrap.hidden=true;success.hidden=false;cart={};localStorage.removeItem('vero-cart');updateCart()};newsletterForm.onsubmit=e=>{e.preventDefault();newsletterMsg.textContent=t('joined');newsletterForm.reset()};langBtn.onclick=()=>{lang=lang==='en'?'ko':'en';langBtn.textContent=lang==='ko'?'English':'한국어';render()};render();
