// Partner preview: sample catalogue, no data collection or real transactions.
Object.assign(copy.en,{announcement:'Partner preview · Sample products and prices · No real purchases',heroNote:'The Seoul collection · Concept edition',newsletterTitle:'Try the tasting-list experience.',thanks:'Demo complete. Your email was not saved or sent.',successTitle:'Your demo order is complete.',successText:'No purchase was made. No payment or personal information was sent.',heroText:'Six Italian-inspired pantry pieces. One memorable evening. Explore a curated gourmet concept for Korea.',storyText:'Vero Seoul is a proposed edit of regional Italian specialties for curious Korean tables. Our sourcing criteria are origin, flavour, shelf life and a story worth sharing. Producers and import arrangements are still to be confirmed.'});
Object.assign(copy.ko,{announcement:'파트너 프리뷰 · 제품과 가격은 예시입니다 · 실제 구매 불가',heroNote:'서울 컬렉션 · 콘셉트 에디션',newsletterTitle:'테이스팅 리스트를 체험해 보세요.',thanks:'데모 완료. 이메일은 저장되거나 전송되지 않았습니다.',successTitle:'데모 주문이 완료되었습니다.',successText:'실제 구매가 아닙니다. 결제 및 개인정보는 전송되지 않았습니다.',heroText:'이탈리아에서 영감을 받은 여섯 가지 팬트리 제품으로 특별한 저녁을. 한국을 위한 고메 브랜드 콘셉트를 만나보세요.',storyText:'베로 서울은 이탈리아 지역 특산품을 한국의 테이블에 소개하기 위한 브랜드 콘셉트입니다. 원산지, 맛, 보관성, 이야기를 기준으로 제품을 선정할 예정이며 생산자와 수입 절차는 아직 확정되지 않았습니다.'});
const drawer=document.getElementById('cartDrawer');
drawer.setAttribute('role','dialog');drawer.setAttribute('aria-modal','true');
const originalOpen=openCart,originalClose=closeCart;
openCart=()=>{originalOpen();document.body.classList.add('bag-open');document.querySelector('main').inert=true;document.querySelector('header').inert=true;document.querySelector('footer').inert=true;document.getElementById('closeCart').focus()};
closeCart=()=>{originalClose();document.body.classList.remove('bag-open');document.querySelector('main').inert=false;document.querySelector('header').inert=false;document.querySelector('footer').inert=false;document.getElementById('cartBtn').focus()};
document.getElementById('cartBtn').onclick=()=>openCart();document.getElementById('closeCart').onclick=()=>closeCart();document.getElementById('overlay').onclick=()=>closeCart();
document.addEventListener('keydown',e=>{if(!drawer.classList.contains('open'))return;if(e.key==='Escape')closeCart();if(e.key==='Tab'){const els=[...drawer.querySelectorAll('button:not(:disabled),a,input')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const baseRenderCart=renderCart;renderCart=()=>{baseRenderCart();document.querySelectorAll('[data-qty]').forEach(b=>b.setAttribute('aria-label',`${Number(b.dataset.delta)>0?(lang==='ko'?'수량 늘리기':'Increase quantity'):(lang==='ko'?'수량 줄이기':'Decrease quantity')}: ${itemName(findItem(b.dataset.qty))}`))};
document.getElementById('checkoutBtn').onclick=()=>{closeCart();document.getElementById('checkoutForm').reset();document.getElementById('checkoutFormWrap').hidden=false;document.getElementById('success').hidden=true;document.getElementById('checkoutDialog').showModal()};
const detail=document.createElement('dialog');detail.id='productDialog';detail.setAttribute('aria-label','Product details');document.body.append(detail);
const baseCards=renderCards;renderCards=(items,target)=>{baseCards(items,target);document.querySelectorAll(`${target} .product-info`).forEach((el,i)=>{const b=document.createElement('button');b.className='product-detail';b.textContent=lang==='ko'?'구성 및 상세 보기 →':'What’s inside →';b.onclick=()=>{const p=items[i];const included={discovery:['sauce','pasta'],date:['sauce','honey','salt','pasta','taralli'],signature:products.map(x=>x.id)}[p.id];detail.innerHTML=`<button class="close" aria-label="Close">×</button><p class="eyebrow">VERO SEOUL</p><h2>${itemName(p)}</h2><p>${lang==='ko'?p.descKo:p.desc}</p>${included?`<ul>${included.map(id=>`<li>${itemName(findItem(id))}</li>`).join('')}</ul>`:''}<p class="detail-price">${won(p.price)}</p><p class="preview-label">${lang==='ko'?'콘셉트 예시입니다. 최종 성분, 알레르기 정보, 원산지 및 유통기한은 공급업체 선정 후 확인됩니다.':'Illustrative concept. Final ingredients, allergens, origin and shelf life will be verified with the selected supplier.'}</p><button class="button dark full" data-add="${p.id}">${copy[lang].add}</button>`;detail.querySelector('.close').onclick=()=>detail.close();detail.showModal()};el.insertBefore(b,el.querySelector('.product-bottom'))})};
translate();
